### ISSUE TITLE
Some more labs

### ISSUE THREAD

**Issue by chubbj** [Zuricho/ProteinDesignLabs#1]
Hey, this is a cool resource. I have some more labs for you:

## United States:

- [Katherine Albanese](https://www.albaneselab.com/), Wake Forest

## United Kingdom

- [Ross Anderson](https://theandersonlab.com/lab-members/ross-anderson/), University of Bristol
- [Fabio Parmeggiani](https://profiles.cardiff.ac.uk/staff/parmeggianif), Cardiff University

## Austria

- [Gustav Orberdorfer](https://www.tugraz.at/institute/ibc/research/research-groups/protein-design), TU Graz

**Comment by Zuricho** [comment]
Thanks, we'll update these soon
