### ISSUE TITLE
Lab suggestions from Vanderbilt

### ISSUE THREAD

**Issue by conjuncts** [Zuricho/ProteinDesignLabs#3]
Hello there, thanks for the great resource. I have for you a few suggested labs from Vanderbilt University.

Zhongyue Yang
https://lab.vanderbilt.edu/zyang-lab/
https://lab.vanderbilt.edu/zyang-lab/publications/

Jens Meiler
https://meilerlab.org/

Stephanie Wankowicz 
https://stephaniewankowicz.github.io/
https://wankowiczlab.com/

Hassane Mchaourab
https://lab.vanderbilt.edu/mchaourab-lab/person/hassane-s-mchaourab-ph-d/

Ben Brown
https://www.bpbrownlab.org/

AI for Protein Dynamics Center
https://www.ai-proteindynamics.org/
https://medschool.vanderbilt.edu/basic-sciences/2024/03/07/vanderbilt-launches-center-for-applied-artificial-intelligence-in-protein-dynamics/

**Comment by Leo-T-Zang** [comment]
Thanks!!
