### ISSUE TITLE
Czech Republic 

### ISSUE THREAD

**Issue by KarelBerka** [Zuricho/ProteinDesignLabs#4]
please add

CZ Czech Republic
Masaryk University - 
Jiri Damborsky - https://loschmidt.chemi.muni.cz/peg/people/jiri-damborsky/ 
Lab website: https://loschmidt.chemi.muni.cz/peg/ 
Protein Engineering Portal: https://loschmidt.chemi.muni.cz/portal/

**Comment by Leo-T-Zang** [comment]
Thanks
